version: '3.8'

services:
  postgres:
    image: postgres
    container_name: personal-vault-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vaultdb
      POSTGRES_USER: vault_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
